config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#dashboard'

  resources :home, only: [] do
    collection do
      get :stream_by_hashtag
      get :stream_by_user
    end
  end

  resources :analytics, only: [] do
    collection do
      get :stream_by_hashtag
      get :dashboard
    end
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < HomeController
  def dashboard
  end

  def stream_by_hashtag
    @topic = 'Byjus'
    render layout: false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_client, only: [:stream_by_hashtag, :stream_by_user]

  def dashboard
  end

  def stream_by_hashtag
    @topic = params[:hashtag]
    render layout: false
  end

  def stream_by_user
    @user = params[:username]
    render layout: false
  end

  private

  def set_client
    @client = TwitterClient.client_object
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analytics/dashboard.slim
.row.d-flex.m-2
  .col-12
    .card.shadow.mx-auto.m-5
      .card-header.bg-primary.text-white
        | Analytics
        span.float-right
          = link_to 'Go to Live Streams', root_path, class: 'btn btn-primary'
      .card-body.h-100
        .row
          .col-12
            .card.h-75.mb-2
              .card-header WordCloud for 'Byjus'
              .card-body
                #wordcloud_container
        .row
          .col-12
            .card.h-75
              .card-header Sentimental Scores for 'Byjus'
              .card-body
                #sent_score_container

app/views/analytics/stream_by_hashtag.js.erb
<%- @client.filter(track: @topic) do |object| %>
  <%- ActionCable.server.broadcast('analytics_by_hash_incoming_channel', message_id: object.text, sentimental_score: $analyser.score(object.text)) if object.is_a?(Twitter::Tweet); %>
<%- end %>

app/views/home/dashboard.slim
.row.d-flex.mx-2
  .col-12
    .card.shadow.mx-auto.m-5
      .card-header.bg-primary.text-white
        | Live Stream
        span.float-right
          = link_to 'Go to Analytics', dashboard_analytics_path, class: 'btn btn-primary'
      .card-body.h-100
        .row
          .col-6
            form.form-inline#form_by_hashtag data-remote='true'
              .form-row
                .form-group
                  = text_field_tag :hashtag, nil, placeholder: 'HashTag', class: 'form-control', id: 'hashtag_input'
                  = button_tag :submit, class: 'btn btn-primary ml-2'
            .tweets_container.overflow-auto#by_hashtag
          .col-6
            form.form-inline#form_by_user data-remote='true'
              .form-row
                .form-group
                  = text_field_tag :username, nil, placeholder: 'User name', class: 'form-control', id: 'user_input'
                  = button_tag :submit, class: 'btn btn-primary ml-2'
            .tweets_container.overflow-auto#by_user

app/views/home/stream_by_hashtag.js.erb
<%- @client.filter(track: @topic) do |object| ActionCable.server.broadcast('tweet_by_hash_incoming_channel', message_id: object.text) if object.is_a?(Twitter::Tweet); end %>

app/views/home/stream_by_user.js.erb
<%- @client.filter(follow: @user) do |object| ActionCable.server.broadcast('tweet_by_user_incoming_channel', message_id: object.text) if object.is_a?(Twitter::Tweet); end %>

app/views/layouts/application.slim
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7 ] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8 ] <html class="no-js lt-ie9" lang="en">
/[if (gt IE 8)|!(IE)] <! --> <html class="no-js" lang="en"> <!--
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=edge"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  title = content_for?(:title) ? yield(:title) : 'Twitter Streamer'

  = javascript_include_tag 'application'
  = stylesheet_link_tag 'application'
  = stylesheet_link_tag "page_specific/#{controller_name}"
  = javascript_include_tag "page_specific/#{controller_name}"
  = csrf_meta_tags

body#page-top class==("controller__#{controller_name} action__#{action_name}")

  = yield